export const CHARACTER_DETAILS_REQUEST = 'CHARACTER_DETAILS_REQUEST';
export const CHARACTER_DETAILS_SUCCESS = 'CHARACTER_DETAILS_SUCCESS';
export const CHARACTER_DETAILS_FAILURE = 'CHARACTER_DETAILS_FAILURE';