export const CHARACTER_DETAILS_REQUEST = "CHARACTER_DETAILS_REQUEST";
export const CHARACTER_DETAILS_SUCCESS = "CHARACTER_DETAILS_SUCCESS";
export const CHARACTER_DETAILS_FAILURE = "CHARACTER_DETAILS_FAILURE";
export const CHARACTER_COMIC_REQUEST = "CHARACTER_COMIC_REQUEST";
export const CHARACTER_COMIC_SUCCESS = "CHARACTER_COMIC_SUCCESS";
export const CHARACTER_COMIC_FAILURE = "CHARACTER_COMIC_FAILURE";
